Delete pregenerated Paths_* modules
Hardcode version information into Distribution.Simple.Utils and
Distribution.Client.Version, which are the only things that still
needed these. Hopefully this will keep `cabal check` from getting
confused:

    Error: [no-autogen-paths] Packages using 'cabal-version: 2.0' and
    the autogenerated module Paths_* must include it also on the
    'autogen-modules' field besides 'exposed-modules' and
    'other-modules'.

Signed-off-by: hololeap <hololeap@protonmail.com>